services:
  api:
    build:
      context: .
      target: api
    restart: unless-stopped

  web:
    build:
      context: .
      target: web
    depends_on:
      - api
    ports:
      - "4040:80"
    restart: unless-stopped
